services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - job-matching-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    networks:
      - job-matching-network

networks:
  job-matching-network:
    driver: bridge

volumes:
  postgres-data: